### ISSUE TITLE
Fail to create/change sub-indices

### ISSUE THREAD

**Issue by spaceKelan** [bggardner/canopen-eds-editor#1]
Hi @bggardner,

your editor seems appealing as it is web-based and therefore platform independent. I tried to create a 1010h which has at least 0x00 and 0x01 as sub-indices but I cannot create nor change any sub-index. Can you please elaborate the steps required to proceed?

This is what I got 
![image](https://github.com/bggardner/canopen-eds-editor/assets/51329415/08576876-ef63-453f-a105-b2f3c68eabb4)

Right now, I am using Firefox 114 on Windows 10. 

Thanks in advance!

**Comment by spaceKelan** [comment]
Thanks!

FYI 
apparently this it the current state in Firefox
![image](https://github.com/bggardner/canopen-eds-editor/assets/51329415/34692464-b948-4463-8c79-c6339bc66873)

but I tried Chrome now and it works there
![image](https://github.com/bggardner/canopen-eds-editor/assets/51329415/12c67d3b-d3a7-4aa5-a0fe-6832fcf35705)

**Comment by bggardner** [comment]
You may need to do a hard refresh so Firefox reloads the (changes to) JavaScript file.
